# Generated by Django 4.0.4 on 2022-04-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0004_alter_cpfcnpj_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.ForeignKey(default='99999999999', on_delete=django.db.models.deletion.CASCADE, to='Pessoas.cpfcnpj'),
        ),
    ]
