# Generated by Django 4.0.4 on 2022-04-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0005_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoas.cpfcnpj', unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(max_length=11),
        ),
    ]
