# Generated by Django 4.0.4 on 2022-04-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0006_alter_cliente_cpf_cnpj_alter_cliente_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pessoas.cpfcnpj'),
        ),
    ]
